#path to output directory
output_dir: "../Output"
#input directory where raw reads are
input_dir       : "../Input"
barcodes: "barcodes.tsv"
#barcode file(barcode file should be kept inside input directory) and enzymes will be included in barcode file
tmpdir        : "../Misc"
#number of sequencing cycles
cycles        : 150
#Sequence Reads
Read1 : "readsF.fq"
Read2 : "readsR.fq"
#Minimal cluster depth
min-depth: 2
#Location of the blastDB
blastDB: "/scratch2/maarten/blastDB"
