barcodefiltered_filename: "barcodes_filtered.tsv"
clonefiltered_dir          : "Preprocessing/Clonefiltered"
preprocessingsup_dir          : "Supplement/Preprocessing" 
genus:          "Supplement/Blasting/Relevant_organisms.csv"


# should be divisible by 4
max_threads: 16

#number of sequencing cycles
cycles        : 150
#Sequence Reads
#Read1 : "readsF.fq.gz"
Read1: "readsFfull.fq.gz"
#Read2 : "readsR.fq.gz"
Read2: "readsRfull.fq.gz"
#Minimal cluster depth
min-depth: 2
#Location of the blastDB
blastDB: "../../../niels/blastdb"

# -- main folders
output_dir    : "../Output"
input_dir     : "../Input"
tmp_dir       : "../Misc"

# -- Preprocessing
barcode_file: "barcodes.tsv"











adapter1: "ATGATACGGCGACCACCGAGATCTACACTCTTTCCCTACACGACGCTCTTCCGATCT" 
adapter2: "CAAGCAGAAGACGGCATACGAGATCGGTCTCGGCATTCCTGCTGAACCGCTCTTCCGATCT"
