output_dir: "../Output"
input_dir       : "../Input"
barcode_filename: "barcodes.tsv"
barcodefiltered_filename: "barcodes_filtered.tsv"
tmp_dir        : "../Misc"
clonefiltered_dir          : "Preprocessing/Clonefiltered"
preprocessingsup_dir          : "Supplement/Preprocessing" 
adapterfile                :  "adapters.txt"

#number of sequencing cycles
cycles        : 150
#Sequence Reads
Read1 : "readsF.fq.gz"
Read2 : "readsR.fq.gz"
#Minimal cluster depth
min-depth: 2
#Location of the blastDB
blastDB: "/scratch2/maarten/blastDB"